name: Aqua
on: pull_request
jobs:
  aqua:
    name: trivy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,config,secret'
          hide-progress: false
          format: 'table'
          # Customizing which severities are scanned for is done by adding the following flag: severity: 'UNKNOWN','LOW','MEDIUM','HIGH','CRITICAL'
        env:
          AQUA_KEY: uS5UZ9LjO0AWGC8F9k11SY
          AQUA_SECRET: I5698tdiD1gorVUMNGEgfdagbStCmBwTHCJ
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: https://api-dev.aquasec.com
          CSPM_URL: https://stage.api.cloudsploit.com
